Traceback (most recent call last):
  File "C:\Users\cxu\Miniconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\cxu\Miniconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\cxu\Miniconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\cxu\Miniconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\cxu\Miniconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\cxu\Miniconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\cxu\Miniconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\cxu\Miniconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
movies_with_director = direct_gross.dropna(subset=["director"])
movie_count = scpt.count_movie(movies_with_director, 'director','movie_title' )

director_count_gross = avg_inflation_gross_by_director.merge(movie_count, left_on='director', right_on='director', how='left', indicator=True)
director_count_gross  =director_count_gross.assign(director_avg_gross_per_movie=director_count_gross['inflation_adjusted_gross'] *director_count_gross['count'])
director_count_gross

#director_count_gross_max = director_count_gross['director_avg_gross_per_movie'].max()
director_count_gross_max=director_count_gross.loc[director_count_gross['director_avg_gross_per_movie'] == director_count_gross['director_avg_gross_per_movie'].max()]
director_count_gross_max
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[4], line 2[0m
[0;32m      1[0m movies_with_director [38;5;241m=[39m direct_gross[38;5;241m.[39mdropna(subset[38;5;241m=[39m[[38;5;124m"[39m[38;5;124mdirector[39m[38;5;124m"[39m])
[1;32m----> 2[0m movie_count [38;5;241m=[39m [43mscpt[49m[38;5;241;43m.[39;49m[43mcount_movie[49m[43m([49m[43mmovies_with_director[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mdirector[39;49m[38;5;124;43m'[39;49m[43m,[49m[38;5;124;43m'[39;49m[38;5;124;43mmovie_title[39;49m[38;5;124;43m'[39;49m[43m [49m[43m)[49m
[0;32m      4[0m director_count_gross [38;5;241m=[39m avg_inflation_gross_by_director[38;5;241m.[39mmerge(movie_count, left_on[38;5;241m=[39m[38;5;124m'[39m[38;5;124mdirector[39m[38;5;124m'[39m, right_on[38;5;241m=[39m[38;5;124m'[39m[38;5;124mdirector[39m[38;5;124m'[39m, how[38;5;241m=[39m[38;5;124m'[39m[38;5;124mleft[39m[38;5;124m'[39m, indicator[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[0;32m      5[0m director_count_gross  [38;5;241m=[39mdirector_count_gross[38;5;241m.[39massign(director_avg_gross_per_movie[38;5;241m=[39mdirector_count_gross[[38;5;124m'[39m[38;5;124minflation_adjusted_gross[39m[38;5;124m'[39m] [38;5;241m*[39mdirector_count_gross[[38;5;124m'[39m[38;5;124mcount[39m[38;5;124m'[39m])

File [1;32m~\Assignment-8\assignment8\Methods and Results\script.py:46[0m, in [0;36mcount_movie[1;34m(data, grouping_col, count_col)[0m
[0;32m     43[0m [38;5;28;01massert[39;00m grouping_col [38;5;129;01min[39;00m data[38;5;241m.[39mcolumns, [38;5;124m"[39m[38;5;124mThe grouping column does not exist in the dataframe[39m[38;5;124m"[39m
[0;32m     45[0m [38;5;66;03m# Tests that the the action column is in the dataframe[39;00m
[1;32m---> 46[0m [38;5;28;01massert[39;00m [43maction_col[49m [38;5;129;01min[39;00m data[38;5;241m.[39mcolumns, [38;5;124m"[39m[38;5;124mThe action column does not exist in the dataframe[39m[38;5;124m"[39m
[0;32m     49[0m [38;5;66;03m# compute the groupby object[39;00m
[0;32m     50[0m tot_movie [38;5;241m=[39m data[38;5;241m.[39mgroupby(grouping_col)[count_col][38;5;241m.[39magg([[38;5;124m'[39m[38;5;124mcount[39m[38;5;124m'[39m])

[1;31mNameError[0m: name 'action_col' is not defined
NameError: name 'action_col' is not defined

